In [52]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from sklearn.preprocessing import OneHotEncoder

In [121]:
X_train = pd.read_csv(r'../Data Sets/Classify Points Problem/Logistic_X_Train.csv').values
y_train = pd.read_csv(r'../Data Sets/Classify Points Problem/Logistic_Y_Train.csv')
X_test = pd.read_csv(r'../Data Sets/Classify Points Problem/Logistic_X_Test.csv').values

In [65]:
X_train.shape

(2250, 2)

In [122]:
y_train

      label
0         0
1         0
2         1
3         0
4         1
5         0
6         0
7         0
8         0
9         1
10        0
11        1
12        1
13        0
14        1
15        0
16        1
17        0
18        1
19        1
20        1
21        0
22        0
23        1
24        0
25        1
26        0
27        0
28        0
29        1
...     ...
2220      0
2221      0
2222      1
2223      1
2224      1
2225      0
2226      1
2227      0
2228      1
2229      0
2230      1
2231      1
2232      1
2233      1
2234      1
2235      1
2236      0
2237      1
2238      0
2239      0
2240      0
2241      0
2242      1
2243      0
2244      0
2245      1
2246      1
2247      1
2248      1
2249      0

[2250 rows x 1 columns]

In [67]:
ohe = OneHotEncoder(categories='auto')

In [68]:
y_hot = ohe.fit_transform(y_train.reshape(-1,1)).todense()

In [69]:
y_hot

matrix([[1., 0.],
        [1., 0.],
        [0., 1.],
        ...,
        [0., 1.],
        [0., 1.],
        [1., 0.]])

In [99]:
model = Sequential()

In [100]:
model.add(Dense(16, activation='relu', input_shape=[2]))
model.add(Dense(8, activation='relu'))
model.add(Dense(4, activation='relu'))
model.add(Dense(2, activation='softmax'))

In [101]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_57 (Dense)             (None, 16)                48
_________________________________________________________________
dense_58 (Dense)             (None, 8)                 136
_________________________________________________________________
dense_59 (Dense)             (None, 4)                 36
_________________________________________________________________
dense_60 (Dense)             (None, 2)                 10
=================================================================
Total params: 230
Trainable params: 230
Non-trainable params: 0
_________________________________________________________________

In [102]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [103]:
model.fit(X_train, y_hot, epochs=40, batch_size=100)

Epoch 1/40
2250/2250 [==============================] - 1s 596us/step - loss: 0.6756 - acc: 0.5347
Epoch 2/40
2250/2250 [==============================] - 0s 32us/step - loss: 0.6486 - acc: 0.7391
Epoch 3/40
2250/2250 [==============================] - 0s 27us/step - loss: 0.6087 - acc: 0.8178
Epoch 4/40
2250/2250 [==============================] - 0s 26us/step - loss: 0.5573 - acc: 0.8351
Epoch 5/40
2250/2250 [==============================] - 0s 30us/step - loss: 0.5103 - acc: 0.8516
Epoch 6/40
2250/2250 [==============================] - 0s 32us/step - loss: 0.4768 - acc: 0.8609
Epoch 7/40
2250/2250 [==============================] - 0s 30us/step - loss: 0.4498 - acc: 0.8738
Epoch 8/40
2250/2250 [==============================] - 0s 28us/step - loss: 0.4239 - acc: 0.8871
Epoch 9/40
2250/2250 [==============================] - 0s 27us/step - loss: 0.4003 - acc: 0.8969
Epoch 10/40
2250/2250 [==============================] - 0s 28us/step - loss: 0.3817 - acc: 0.9067
Epoch 11/40
2250/2250 [==============================] - 0s 30us/step - loss: 0.3651 - acc: 0.9116
Epoch 12/40
2250/2250 [==============================] - 0s 31us/step - loss: 0.3501 - acc: 0.9196
Epoch 13/40
2250/2250 [==============================] - 0s 33us/step - loss: 0.3358 - acc: 0.9218
Epoch 14/40
2250/2250 [==============================] - 0s 34us/step - loss: 0.3224 - acc: 0.9329
Epoch 15/40
2250/2250 [==============================] - 0s 31us/step - loss: 0.3101 - acc: 0.9324
Epoch 16/40
2250/2250 [==============================] - 0s 30us/step - loss: 0.2974 - acc: 0.9396
Epoch 17/40
2250/2250 [==============================] - 0s 27us/step - loss: 0.2866 - acc: 0.9413
Epoch 18/40
2250/2250 [==============================] - 0s 28us/step - loss: 0.2751 - acc: 0.9471
Epoch 19/40
2250/2250 [==============================] - 0s 27us/step - loss: 0.2652 - acc: 0.9507
Epoch 20/40
2250/2250 [==============================] - 0s 28us/step - loss: 0.2560 - acc: 0.9547
Epoch 21/40
2250/2250 [==============================] - 0s 29us/step - loss: 0.2478 - acc: 0.9538
Epoch 22/40
2250/2250 [==============================] - 0s 30us/step - loss: 0.2391 - acc: 0.9556
Epoch 23/40
2250/2250 [==============================] - 0s 31us/step - loss: 0.2317 - acc: 0.9573
Epoch 24/40
2250/2250 [==============================] - 0s 27us/step - loss: 0.2248 - acc: 0.9582
Epoch 25/40
2250/2250 [==============================] - 0s 30us/step - loss: 0.2184 - acc: 0.9587
Epoch 26/40
2250/2250 [==============================] - 0s 30us/step - loss: 0.2125 - acc: 0.9627
Epoch 27/40
2250/2250 [==============================] - 0s 29us/step - loss: 0.2079 - acc: 0.9613
Epoch 28/40
2250/2250 [==============================] - 0s 25us/step - loss: 0.2025 - acc: 0.9622
Epoch 29/40
2250/2250 [==============================] - 0s 29us/step - loss: 0.1975 - acc: 0.9644
Epoch 30/40
2250/2250 [==============================] - 0s 32us/step - loss: 0.1927 - acc: 0.9627
Epoch 31/40
2250/2250 [==============================] - 0s 35us/step - loss: 0.1894 - acc: 0.9622
Epoch 32/40
2250/2250 [==============================] - 0s 30us/step - loss: 0.1846 - acc: 0.9622
Epoch 33/40
2250/2250 [==============================] - 0s 29us/step - loss: 0.1812 - acc: 0.9640
Epoch 34/40
2250/2250 [==============================] - 0s 28us/step - loss: 0.1773 - acc: 0.9644
Epoch 35/40
2250/2250 [==============================] - 0s 29us/step - loss: 0.1741 - acc: 0.9640
Epoch 36/40
2250/2250 [==============================] - 0s 29us/step - loss: 0.1720 - acc: 0.9627
Epoch 37/40
2250/2250 [==============================] - 0s 35us/step - loss: 0.1693 - acc: 0.9640
Epoch 38/40
2250/2250 [==============================] - 0s 33us/step - loss: 0.1666 - acc: 0.9640
Epoch 39/40
2250/2250 [==============================] - 0s 30us/step - loss: 0.1627 - acc: 0.9640
Epoch 40/40
2250/2250 [==============================] - 0s 30us/step - loss: 0.1600 - acc: 0.9640

In [105]:
out = model.predict(X_test)

In [107]:
out

array([[9.9932957e-01, 6.7044637e-04],
       [9.9998987e-01, 1.0189015e-05],
       [1.6451016e-01, 8.3548987e-01],
       ...,
       [9.9213129e-01, 7.8687323e-03],
       [9.9992824e-01, 7.1706520e-05],
       [9.0345711e-01, 9.6542932e-02]], dtype=float32)

In [118]:
y_pred = np.argmax(out, axis=1)
y_pred = y_pred.reshape(-1, 1)

In [119]:
df = pd.DataFrame({'label':y_pred[:, 0]})

In [120]:
df.head()

   label
0      0
1      0
2      1
3      0
4      1

In [123]:
# df.to_csv(r'../Data Sets/Classify Points Problem/Prediction.csv', )